# Generated by Django 6.0.2 on 2026-02-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usoequipamento',
            old_name='data_fim',
            new_name='data_devolucao',
        ),
        migrations.RenameField(
            model_name='usoequipamento',
            old_name='data_inicio',
            new_name='data_retirada',
        ),
        migrations.RemoveField(
            model_name='usoequipamento',
            name='observacoes',
        ),
    ]
